#!/bin/sh

set_loader_conf "exec=copy_staging enable"

set_device_hint \
  hint.hdaa.0.nid19.config="as=1 seq=0" \
  hint.hdaa.0.nid20.config="as=1 seq=2" \
  hint.hdaa.0.nid23.config="as=1 seq=1" \
  hint.hdaa.0.nid24.config="as=1 seq=2" \
  hint.hdaa.0.nid26.config="as=1 seq=1" \
  hint.hdaa.0.nid27.config="as=1 seq=2" \
  hint.hdaa.0.nid30.config="as=1 seq=1" \
  hint.hdaa.0.nid33.config="as=1 seq=15 device=Headphones"
