#!/bin/sh

# Generate using: https://github.com/iv-org/youtube-trusted-session-generator
: ${invidious_po_token:='changeme'}
: ${invidious_visitor_data:='changeme'}
: ${invidious_hmac_key:='changemeeeeeeeeeeee'}
: ${invidious_username:='s-invidious'}
: ${invidious_password:='changeme'}
: ${invidious_dbname:='invidious'}
: ${invidious_dbhost:="$postgres_host"}
: ${invidious_fqdn:="$fqdn"}
: ${invidious_repo='https://github.com/iv-org/invidious'}
: ${invidious_branch='master'}
: ${invidious_companion_repo='https://github.com/iv-org/invidious-companion'}
: ${invidious_companion_branch='master'}
: ${invidious_companion_port='8282'}
: ${invidious_companion_secret_key='changeme'}

invidious_dn="uid=${invidious_username},${robots_basedn}"
invidious_local_username=$nginx_user
invidious_home=/usr/local/invidious
invidious_port=8080
invidious_repo_dir="${invidious_home}/invidious.git"
invidious_companion_repo_dir="${invidious_home}/invidious-companion.git"
invidious_companion_cache_dir=/var/db/invidious-companion
invidious_https_cert="${nginx_conf_dir}/invidious.crt"
invidious_https_key="${nginx_conf_dir}/invidious.key"

# Install required packages.
pkg install -y \
  ca_root_nss \
  git \
  crystal \
  shards \
  sqlite3 \
  nginx \
  postgresql${postgresql_version}-client \
  deno \
  gmake

# Create invidious user account.
ldap_add "$invidious_dn" <<EOF
objectClass: account
objectClass: simpleSecurityObject
uid: ${invidious_username}
userPassword: {SSHA-512}
EOF

# Set LDAP password for invidious user.
ldap_passwd "$invidious_dn" "$invidious_password"

# Create postgres user and database.
postgres_create_role "$invidious_dbhost" "$invidious_username"
postgres_create_database "$invidious_dbhost" "$invidious_dbname" "$invidious_username"

# Create invidious home directory.
install_directory -o "$invidious_local_username" -g "$invidious_local_username" -m 0775 "$invidious_home"

# Clone invidious-companion git repo.
[ -d "${invidious_companion_repo_dir}" ] || su -m "$invidious_local_username" -c \
  "git clone ${invidious_companion_repo} ${invidious_companion_repo_dir}"

# Update invidious-companion git repo.
su -m "$invidious_local_username" -c "git -C ${invidious_companion_repo_dir} pull --ff-only"
su -m "$invidious_local_username" -c "git -C ${invidious_companion_repo_dir} switch ${invidious_companion_branch}"

# Build invidious-companion.
# `deno task` is busted on FreeBSD, so we must hardcode the build incantation into a custom script
#  https://github.com/denoland/deno/issues/31087
install_template -m 0555 /usr/local/libexec/invidious-companion-build
( cd "$invidious_companion_repo_dir"
  su -m "$invidious_local_username" -c /usr/local/libexec/invidious-companion-build
)

# Clone invidious git repo.
[ -d "${invidious_repo_dir}" ] || su -m "$invidious_local_username" -c \
  "git clone ${invidious_repo} ${invidious_repo_dir}"

# Update invidious git repo.
su -m "$invidious_local_username" -c "git -C ${invidious_repo_dir} pull --ff-only"
su -m "$invidious_local_username" -c "git -C ${invidious_repo_dir} switch ${invidious_branch}"

# Build invidious.
( cd "$invidious_repo_dir"
  su -m "$invidious_local_username" -c "HOME=${invidious_home} SSL_CERT_DIR=/etc/ssl/certs gmake"
)

# Copy invidious configuration.
install_template -o "$invidious_local_username" -g "$invidious_local_username" -m 0600 "${invidious_repo_dir}/config/config.yml"
install_template -o "$invidious_local_username" -g "$invidious_local_username" -m 0600 "${invidious_companion_repo_dir}/config/config.toml"

# Copy invidious rc script.
install_file -m 0555 \
  /usr/local/etc/rc.d/invidious \
  /usr/local/etc/rc.d/invidious_companion

# Copy TLS certificate for nginx.
install_certificate     invidious "$invidious_https_cert"
install_certificate_key invidious "$invidious_https_key"

# Generate nginx configuration.
install_template -m 0644 \
  /usr/local/etc/nginx/nginx.conf \
  /usr/local/etc/nginx/vhosts.conf
install_file -m 0644 /etc/newsyslog.conf.d/nginx.conf

# Start daemons.
sysrc -v \
  invidious_companion_enable=YES \
  invidious_enable=YES \
  invidious_env="SSL_CERT_DIR=/etc/ssl/certs" \
  nginx_enable=YES
service invidious_companion restart
service invidious restart
service nginx restart

# Copy invidous auto-update script.
install_file -m 0555 \
  /usr/local/libexec/invidious-update \
  /usr/local/libexec/invidious-companion-update
install_template -m 0644 /etc/cron.d/invidious
