#!/bin/sh

site=myhomelab
domain=idm.example.com
email_domain=example.com
locale=en_US.UTF-8
ntp_pools='pool.ntp.org'
root_password=changeme
root_authorized_keys='ssh-ed25519 changeme
ssh-ed25519 changeme'
root_mail_alias="you@${email_domain}"
smtp_host_ip=1.2.3.4
timezone=America/New_York

nproc=$(nproc)

allowed_tcp_ports=ssh
bootstrap_resolvers='1.1.1.1'
fqdn="${BOXCONF_HOSTNAME}.${domain}"
smtp_host="smtp.${domain}"
ssh_authzkeys_user=_authzkeys
tcp_buffer_size=2097152  # suitable for 1 GigE

nginx_nofile=2048
nginx_worker_connections=768
if $(( nproc > 4 )); then
  nginx_worker_processes=4
else
  nginx_worker_processes=$nproc
fi

if [ "${idm_bootstrap:-}" = true ]; then
  resolvers=$bootstrap_resolvers
fi
