#!/bin/sh

site=myhomelab
domain=idm.example.com
email_domain=example.com
locale=en_US.UTF-8
ntp_pools='pool.ntp.org'
root_password=changeme
boxconf_password=changeme
root_authorized_keys='ssh-ed25519 changeme
ssh-ed25519 changeme'
root_mail_alias="you@${email_domain}"
smtp_host_ip=1.2.3.4
pkg_host_ip=1.2.3.4
timezone=America/New_York

# hostname  id  ipv4
idm_server_list="\
idm1      1   1.2.3.4
idm2      2   5.6.7.8"

reverse_dns_zones="0.168.192.in-addr.arpa  12.11.10.in-addr.arpa"

rspamd_privkey='changeme with: rspamadm keypair'
rspamd_pubkey='changeme with: rspamadm keypair'
rspamd_ro_password='changeme'
rspamd_rw_password='changeme'


###############################################################################
# Variables following this line do not (generally) need to be changed.
###############################################################################
nproc=$(nproc)

allowed_tcp_ports=ssh
bootstrap_resolvers='1.1.1.1'
desktop_type=kde
graphics_type=intel
boxconf_username='s-boxconf'
host_keytab_groupname=hostkeytab
host_keytab_gid=788
krb5_ticket_lifetime=24h
krb5_renew_lifetime=7d
nslcd_min_uid=1000
nscd_ttl=600
nscd_negative_ttl=20
rspamd_port=11334
ssh_authzkeys_uid=789
ssh_authzkeys_username=sshkeys
tcp_buffer_size=2097152  # suitable for 1 GigE

nginx_nofile=2048
nginx_worker_connections=768
if $(( nproc > 4 )); then
  nginx_worker_processes=4
else
  nginx_worker_processes=$nproc
fi
