#!/bin/sh

allow_wx=1
allow_proc_debug=0
cx_lowest=Cmax
enable_pf=true
install_packages='sudo tmux vim'
intel_epp=50
see_other_uids=0
clear_tmp_enable=true

memsize=$(sysctl -n hw.physmem)

export ASSUME_ALWAYS_YES=yes
devfs_local_ruleset_name=localrules
keytab_dir=/var/db/keytabs
nfscbd_port=7745
nginx_user=www
nginx_conf_dir=/usr/local/etc/nginx
nslcd_user=nslcd
php_version=82
postgresql_version=16
python_version=311
saslauthd_runtime_dir=/var/run/saslauthd
saslauthd_user=cyrus
site_cacert_path=/usr/local/etc/ssl/certs/ca.crt
system_cacert_path=/etc/ssl/certs
ssh_host_key_dir=/var/db/ssh
xdg_override_dir=/usr/local/share-override

# For 10 Gbit ethernet, bump up the TCP buffers.
if ifconfig | grep -q '10Gbase-T'; then
  tcp_buffer_size=16777216
fi

case $BOXCONF_VIRTUALIZATION_TYPE in
  jail)
    # For jails, the state dataset is delegated to the jail and named "data".
    state_dataset=$(zfs list -Ho jailed,name | awk '$1 == "on" && $2 ~ /\/data$/ {print $2;exit}')
    ;;
  *)
    # Otherwise, assume the state dataset is named "data" in the root zpool.
    root_zpool=$(zfs list -Ho name,mountpoint | awk '$2 == "/" {print $1;exit}' | cut -d/ -f1)
    if [ -n "$root_zpool" ]; then
      state_dataset="${root_zpool}/data"
    fi
    ;;
esac
