#!/bin/sh

cat <<EOF | debconf-set-selections
locales locales/default_environment_locale multiselect en_US.UTF-8
locales locales/locales_to_be_generated    multiselect en_US.UTF-8
EOF

localectl set-locale en_US.UTF-8
