#!/bin/sh

sysrc -v \
  clear_tmp_enable=YES \
  dumpdev=NO \
  ipv6_activate_all_interfaces=NO \
  syslogd_flags=-ss

if [ -n "${console_font:-}" ]; then
  sysrc -v allscreens_flags="-f ${console_font}"
fi
