#!/bin/sh

# Jails don't need NTP.
if [ "$BOXCONF_VIRTUALIZATION_TYPE" = jail ]; then
  return
fi

install_template -m 0644 /etc/ntp.conf

sysrc -v \
  ntpd_enable=YES \
  ntpd_sync_on_start=YES

chown ntpd /var/db/ntp/ntpd.pid
service ntpd restart
