#!/bin/sh

# Create local CA certificates directory.
install_directory -m 0755  \
  /usr/local/share         \
  /usr/local/share/certs   \
  /usr/local/share/certs/trusted

# Install our root CA.
install_ca_certificate "$site_cacert_path"

certctl rehash
