#!/bin/sh

if [ "$BOXCONF_HOSTCLASS" = smtp_server ] || [ "${enable_mail:-}" = false ]; then
  return
fi

# Configure local mail agent.
install_template -m 0644 /etc/dma/dma.conf
install_template -m 0644 /etc/aliases
