#!/bin/sh

desktop_access_role='desktop-access'
login_access_groups="${login_access_groups:-} ${desktop_access_role}"

# Let users run gdb/truss.
allow_proc_debug=1

# Serial console breaks ConsoleKit2.
enable_serial_console=false

# UID/GID hiding breaks consolekit and KDE screen locker.
see_other_uids=1

# sndiod's control socket lives under /tmp, but sndoid starts *before* /tmp is
# cleared out, resulting in the socket being blown away.
clear_tmp_enable=false

# Chromium seems to need this to enable VAAPI video decoding on intel.
chrome_flags='--enable-features=Vulkan,VulkanFromANGLE,DefaultANGLEVulkan'

# signal-desktop requires pulseaudio for audio/video chat. SAD!
desktop_common_packages="
bind-tools
cantarell-fonts
chromium
droid-fonts-ttf
eclipse
ffmpeg
firefox
git
gnupg
inconsolata-ttf
krb5
libreoffice
libva-utils
libvdpau-va-gl
neofetch
noto-basic
noto-emoji
password-store
postgresql16-client
pulseaudio
py${python_version}-pip
rsync
signal-desktop
sndio
stow
terminus-font
terminus-ttf
tmux
tree
ubuntu-font
vdpauinfo
v4l-utils
v4l_compat
webcamd
webfonts 
wireguard-tools
xorg"

desktop_kde_packages="
audacious-qt5
audacious-plugins-qt5
digikam
dino
elisa
gajim
gtksourceview4
k3b
kde5
kid3-kf5
kmix
konversation
py${python_version}-omemo-dr
sddm"

desktop_i3_packages='
compton
dunst
dmenu
i3
i3lock
i3status
profanity
xfontsel
xidle
xterm'
