#!/bin/sh

desktop_access_role='desktop-access'
login_access_groups="${login_access_groups:-} ${desktop_access_role}"

# Video chat with others on the local network requires UDP ports for RTP/WebRTC
allowed_udp_ports='1024:65535'

# I don't want desktops to suspend or hibernate.
polkit_disable_suspend=true

# Let users run gdb/truss.
allow_proc_debug=1

# Serial console breaks ConsoleKit2.
enable_serial_console=false

# UID/GID hiding breaks consolekit and KDE screen locker.
see_other_uids=1

# sndiod's control socket lives under /tmp, but sndoid starts *before* /tmp is
# cleared out, resulting in the socket being blown away.
clear_tmp_enable=false

# Chromium seems to need this to enable VAAPI video decoding on intel.
chrome_flags='--enable-features=Vulkan,VulkanFromANGLE,DefaultANGLEVulkan'

gajim_packages="
gajim
py${python_version}-omemo-dr
farstream
gsound"

# signal-desktop requires pulseaudio for audio/video chat. SAD!
# Also, freedesktop-sound-theme is required for notification sounds in Dino
desktop_common_packages="
android-tools
bind-tools
ca_root_nss
cantarell-fonts
chromium
droid-fonts-ttf
eclipse
ffmpeg
firefox
git
gnupg
hs-pandoc
inconsolata-ttf
jq
krb5
libreoffice
libva-utils
libvdpau-va-gl
neofetch
noto-basic
noto-emoji
password-store
pdftk
postgresql16-client
pulseaudio
python
py${python_version}-pip
roboto-fonts-ttf
rsync
freedesktop-sound-theme
signal-desktop
sndio
stow
terminus-font
terminus-ttf
thunderbird
tmux
tree
ubuntu-font
vdpauinfo
v4l-utils
v4l_compat
webcamd
webfonts 
wireguard-tools
xorg"

desktop_kde_packages="
android-file-transfer-qt5
audacious-qt5
audacious-plugins-qt5
digikam
dino
elisa
${gajim_packages}
gtksourceview4
k3b
kde5
kid3-kf5
kmix
konversation
en-hunspell
merkuro
sddm"

desktop_i3_packages='
compton
dunst
dmenu
i3
i3lock
i3status
profanity
xfontsel
xidle
xterm'
