#!/bin/sh

BOXCONF_LDAP_SASL=true

allowed_tcp_ports='ssh ldap ldaps domain kerberos-sec kerberos-adm'
allowed_udp_ports='domain kerberos-sec kpasswd'

enable_idm=false

kdc_master_key='changeme'

ssh_authorized_keys_user=nobody

unbound_blocklists="\
hagezi-pro  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/rpz/pro.txt"
